/* ============================================================
   products-data.js — Product Catalogue & Category Data
   All product data in one place. Easy to extend.
   ============================================================ */

const CATEGORIES = [
  { id: 'all',         label: 'All'           },
  { id: 'electronics', label: 'Electronics'   },
  { id: 'fashion',     label: 'Fashion'       },
  { id: 'home',        label: 'Home & Kitchen'},
  { id: 'books',       label: 'Books'         },
  { id: 'sports',      label: 'Sports'        },
  { id: 'beauty',      label: 'Beauty'        },
  { id: 'toys',        label: 'Toys'          },
];

const CATEGORY_CARDS = [
  {
    id:    'electronics',
    name:  'Electronics',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=400&h=220&fit=crop',
    badge: null,
  },
  {
    id:    'fashion',
    name:  'Fashion',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=220&fit=crop',
    badge: 'Hot',
  },
  {
    id:    'home',
    name:  'Home & Kitchen',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=220&fit=crop',
    badge: null,
  },
  {
    id:    'books',
    name:  'Books',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=220&fit=crop',
    badge: 'New',
  },
  {
    id:    'sports',
    name:  'Sports & Outdoors',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400&h=220&fit=crop',
    badge: null,
  },
  {
    id:    'beauty',
    name:  'Beauty',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=220&fit=crop',
    badge: null,
  },
  {
    id:    'toys',
    name:  'Toys & Games',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=220&fit=crop',
    badge: null,
  },
  {
    id:    'automotive',
    name:  'Automotive',
    cta:   'Shop now',
    img:   'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=400&h=220&fit=crop',
    badge: null,
  },
];

const PRODUCTS = [
  /* ── Electronics ───────────────────────────────────────── */
  {
    id:         1,
    title:      'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    category:   'electronics',
    price:      299.99,
    original:   349.99,
    rating:     4.7,
    reviews:    14823,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
    description:'Industry-leading noise cancelling with Dual Noise Sensor technology.',
  },
  {
    id:         2,
    title:      'Apple iPad Air 10.9" (5th Gen) — Wi-Fi 64GB Space Grey',
    category:   'electronics',
    price:      499.00,
    original:   599.00,
    rating:     4.8,
    reviews:    8230,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery Saturday',
    img:        'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
    description:'Powerful. Colourful. Wonderful. iPad Air comes with M1 chip.',
  },
  {
    id:         3,
    title:      'Samsung 4K Smart TV 55" QLED Crystal Display',
    category:   'electronics',
    price:      649.99,
    original:   899.99,
    rating:     4.6,
    reviews:    5641,
    badge:      'hot',
    badgeText:  'Hot Deal',
    prime:      true,
    delivery:   'FREE delivery this week',
    img:        'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&h=400&fit=crop',
    description:'Vivid QLED display with Quantum Processor and built-in Alexa.',
  },
  {
    id:         4,
    title:      'Logitech MX Master 3S Wireless Performance Mouse',
    category:   'electronics',
    price:      89.99,
    original:   99.99,
    rating:     4.9,
    reviews:    21004,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop',
    description:'8K DPI sensor, ultra-fast scroll wheel, and 70-day battery life.',
  },
  /* ── Fashion ────────────────────────────────────────────── */
  {
    id:         5,
    title:      'Nike Air Max 270 React Men\'s Running Shoes',
    category:   'fashion',
    price:      129.95,
    original:   160.00,
    rating:     4.5,
    reviews:    9872,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
    description:'Maximum cushioning meets streetwear style in every step.',
  },
  {
    id:         6,
    title:      'Levi\'s 501 Original Fit Jeans — Classic Blue',
    category:   'fashion',
    price:      59.99,
    original:   79.99,
    rating:     4.4,
    reviews:    34500,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery Saturday',
    img:        'https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=400&h=400&fit=crop',
    description:'The original and most iconic style since 1873.',
  },
  {
    id:         7,
    title:      'Fossil Women\'s Gen 6 Hybrid Smartwatch Gold Tone',
    category:   'fashion',
    price:      175.00,
    original:   215.00,
    rating:     4.3,
    reviews:    2100,
    badge:      'new',
    badgeText:  'New',
    prime:      false,
    delivery:   'Arrives in 3–5 days',
    img:        'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
    description:'Classic analog design with health & fitness tracking inside.',
  },
  {
    id:         8,
    title:      'The North Face Women\'s Thermoball Eco Jacket',
    category:   'fashion',
    price:      149.95,
    original:   220.00,
    rating:     4.7,
    reviews:    4300,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
    description:'Compressible insulation made from 100% recycled materials.',
  },
  /* ── Home & Kitchen ─────────────────────────────────────── */
  {
    id:         9,
    title:      'Instant Pot Duo 7-in-1 Electric Pressure Cooker 6 Qt',
    category:   'home',
    price:      79.95,
    original:   99.00,
    rating:     4.8,
    reviews:    98203,
    badge:      'hot',
    badgeText:  'Best Seller',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1585837575652-267f54f5c891?w=400&h=400&fit=crop',
    description:'7 appliances in 1: pressure cooker, slow cooker, rice cooker & more.',
  },
  {
    id:         10,
    title:      'Dyson V15 Detect Cordless Vacuum with Laser Dust Detection',
    category:   'home',
    price:      649.99,
    original:   749.99,
    rating:     4.6,
    reviews:    6700,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery Saturday',
    img:        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    description:'See hidden dust with scientifically proven laser technology.',
  },
  {
    id:         11,
    title:      'Nespresso Vertuo Plus Coffee Machine with Aeroccino',
    category:   'home',
    price:      179.00,
    original:   210.00,
    rating:     4.5,
    reviews:    15200,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop',
    description:'Barcode technology reads the capsule to brew the perfect cup.',
  },
  {
    id:         12,
    title:      'IKEA KALLAX Shelf Unit — White, 77×77cm',
    category:   'home',
    price:      49.99,
    original:   65.00,
    rating:     4.2,
    reviews:    8100,
    badge:      null,
    badgeText:  '',
    prime:      false,
    delivery:   'Arrives in 5–7 days',
    img:        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop',
    description:'Versatile shelf unit you can use as room divider, storage, and more.',
  },
  /* ── Books ──────────────────────────────────────────────── */
  {
    id:         13,
    title:      'Atomic Habits by James Clear — Hardcover',
    category:   'books',
    price:      14.99,
    original:   27.00,
    rating:     4.9,
    reviews:    112430,
    badge:      'hot',
    badgeText:  'Best Seller',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=400&fit=crop',
    description:'The #1 New York Times bestseller on building good habits.',
  },
  {
    id:         14,
    title:      'Dune by Frank Herbert — Paperback',
    category:   'books',
    price:      9.99,
    original:   17.00,
    rating:     4.8,
    reviews:    55000,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop',
    description:'Winner of the Hugo and Nebula Awards. The greatest SF novel ever written.',
  },
  /* ── Sports ─────────────────────────────────────────────── */
  {
    id:         15,
    title:      'Fitbit Charge 5 Advanced Fitness & Health Tracker',
    category:   'sports',
    price:      129.95,
    original:   179.95,
    rating:     4.4,
    reviews:    32100,
    badge:      'sale',
    badgeText:  'Sale',
    prime:      true,
    delivery:   'FREE delivery Saturday',
    img:        'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
    description:'Built-in GPS, stress management score, and 7-day battery.',
  },
  {
    id:         16,
    title:      'Bowflex SelectTech 552 Adjustable Dumbbells (Pair)',
    category:   'sports',
    price:      349.00,
    original:   429.00,
    rating:     4.7,
    reviews:    19800,
    badge:      'hot',
    badgeText:  'Hot Deal',
    prime:      true,
    delivery:   'FREE delivery this week',
    img:        'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=400&fit=crop',
    description:'15 sets of weights in one with a dial system that adjusts 5–52.5 lbs.',
  },
  /* ── Beauty ─────────────────────────────────────────────── */
  {
    id:         17,
    title:      'L\'Oréal Paris Elvive Extraordinary Oil Serum 100ml',
    category:   'beauty',
    price:      12.99,
    original:   16.99,
    rating:     4.6,
    reviews:    23400,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop',
    description:'Luxury oil serum for dry and damaged hair. Up to 6x less breakage.',
  },
  {
    id:         18,
    title:      'Neutrogena Hydro Boost Water Gel Face Moisturiser 50ml',
    category:   'beauty',
    price:      16.99,
    original:   21.99,
    rating:     4.7,
    reviews:    41200,
    badge:      'new',
    badgeText:  'New',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop',
    description:'Oil-free gel cream with hyaluronic acid for non-stop hydration.',
  },
  /* ── Toys ───────────────────────────────────────────────── */
  {
    id:         19,
    title:      'LEGO Technic Formula E Porsche 99X Electric Race Car',
    category:   'toys',
    price:      69.99,
    original:   89.99,
    rating:     4.9,
    reviews:    7630,
    badge:      'hot',
    badgeText:  'Hot Deal',
    prime:      true,
    delivery:   'FREE delivery tomorrow',
    img:        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
    description:'Build and display the iconic electric race car. 390 pieces.',
  },
  {
    id:         20,
    title:      'Hasbro Monopoly Classic Board Game Family Edition',
    category:   'toys',
    price:      24.99,
    original:   34.99,
    rating:     4.5,
    reviews:    89000,
    badge:      null,
    badgeText:  '',
    prime:      true,
    delivery:   'FREE delivery Saturday',
    img:        'https://images.unsplash.com/photo-1611996575749-79a3a250f948?w=400&h=400&fit=crop',
    description:'The classic property trading game for the whole family.',
  },
];

/* ── Hero Slides Data ───────────────────────────────────────── */
const HERO_SLIDES = [
  {
    tag:      'Limited Time Deal',
    title:    'Unbox Great Deals on Electronics',
    subtitle: 'Save big on headphones, tablets, TVs and more. Free delivery on orders over R500.',
    cta:      'Shop Electronics',
    ctaHref:  '#products',
    bg:       'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1400&h=400&fit=crop',
    align:    'left',
  },
  {
    tag:      "Today's Offers",
    title:    'Style Meets Comfort This Season',
    subtitle: 'Discover top fashion brands at unbeatable prices. New arrivals every day.',
    cta:      'Shop Fashion',
    ctaHref:  '#products',
    bg:       'https://images.unsplash.com/photo-1445205170230-053b83016050?w=1400&h=400&fit=crop',
    align:    'left',
  },
  {
    tag:      'Amazon Prime',
    title:    'Your Smart Home Upgrade Starts Here',
    subtitle: 'Get free same-day delivery on home essentials and kitchen must-haves.',
    cta:      'Shop Home',
    ctaHref:  '#products',
    bg:       'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1400&h=400&fit=crop',
    align:    'left',
  },
  {
    tag:      'Books & More',
    title:    'Feed Your Mind with Great Reads',
    subtitle: 'Bestsellers, new releases, and timeless classics at the best prices.',
    cta:      'Shop Books',
    ctaHref:  '#products',
    bg:       'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=1400&h=400&fit=crop',
    align:    'left',
  },
];
